name: Build and Release Custom JRE

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install JDK
      uses: actions/setup-java@v2
      with:
        java-version: '22' # or any version you prefer
        
    - name: check directory
      run: ls 

    - name: Build Custom JRE
      run: |
        mkdir custom-jre
        %JAVA_HOME%\bin\jlink ^
          --module-path %JAVA_HOME%\jmods ^
          --add-modules <your modules> ^
          --output custom-jre

    - name: Archive Custom JRE
      uses: actions/upload-artifact@v2
      with:
        name: custom-jre
        path: custom-jre

  release:
    needs: build
    runs-on: windows-latest

    steps:
    - name: Download Custom JRE
      uses: actions/download-artifact@v2
      with:
        name: custom-jre
        path: custom-jre

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.sha }}
        release_name: Release ${{ github.sha }}
        body: |
          Release ${{ github.sha }}
        draft: false
        prerelease: false

    - name: Upload Custom JRE
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./custom-jre
        asset_name: custom-jre-${{ github.sha }}.zip
        asset_content_type: application/zip
        token: ${{ secrets.GITHUB_TOKEN }}
